import csv

class ColonyAnalyzer:

    ## no constructor necessary since the class creates its own data structures and writes them to a file

    def analyze_colony(self, colony):
        ## access instance data of colony objects and extract data
        ## data will probably be read in from arrays of cell objects generated by the colony class
        ## cell objects include boolean and float attributes that carry values such as presence of antibiotic resistance
        ## calculate statistics including ratio of resistant/nonresistant bacteria, mortality rate of bacteria?, etc.
        ## export/save data in readable format as .csv file
        num_cells = len() # <-- len() argument will be added after colony attributes have been determined
        ## add counters that track numbers of resistant/nonresistant cells, etc.
        for i in range(num_cells):
            ## add code that extracts attributes of each cell and modifies counters accordingly

    ## data parameter type is TBD
    def write_to_csv(self, data):
        with open('colony_analysis.csv', mode = 'w') as colony_analysis:
            file_writer = csv.writer(colony_analysis, delimiter = ", ", quotechar = '"', quoting = csv.QUOTE_MINIMAL)
            ## loop command to write elements of array/list --> file_writer.writerow()
