import csv

class ColonyAnalyzer:

    ## no constructor necessary since the class creates its own data structures and writes them to a file

    def analyze_colony(self, colony):
        ## access instance data of colony objects and extract data
        ## data will probably be read in from arrays of cell objects generated by the colony class
        ## cell objects include boolean and float attributes that carry values such as presence of antibiotic resistance
        ## calculate statistics including ratio of resistant/nonresistant bacteria, mortality rate of bacteria?, etc.
        ## export/save data in readable format as .csv file
        num_cells = len() # <-- len() argument will be added after colony attributes have been determined
        ## add counters that track numbers of resistant/nonresistant cells, etc.
        for i in range(num_cells):
            ## add code that extracts attributes of each cell and modifies counters accordingly
            pass
        
    ## data parameter type is TBD
    def write_to_csv(self, data):
        with open('colony_analysis.csv', mode = 'w') as colony_analysis:
            file_writer = csv.writer(colony_analysis, delimiter = ", ", quotechar = '"', quoting = csv.QUOTE_MINIMAL)
            ## loop command to write elements of array/list --> file_writer.writerow()
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import gaussian_kde

# These are just sample numbers, the actual data needs to be inputted once found 
x = np.random.normal(size=1000)
y = x * 3 + np.random.normal(size=1000)

# Calculate the point density
xy = np.vstack([x,y])
z = gaussian_kde(xy)(xy)

fig, ax = plt.subplots()
ax.scatter(x, y, c=z, s=100, edgecolor='')
plt.show()